spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: lotus-market

  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_URL:localhost:27017}/${DB_NAME}?authSource=${DB_NAME}

server:
  port: 8765

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true

gcp:
  bucket:
    name: k8s-kimjc
