apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-pv
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /PORTAINER-DATA
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [k8s-2-node1]}
