apiVersion: v1
kind: ResourceQuota
metadata:
  name: back-ops-rq
  namespace: back-ops
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "6Gi"
    limits.cpu: "6"
    limits.memory: "8Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: back-ops-lr
  namespace: back-ops
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "1"
      memory: "2Gi"
    default:
      cpu: "2"
      memory: "3Gi"
    max:
      cpu: "3"
      memory: "4Gi"
