apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: ops-user-back-binding
  namespace: back-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ops-user-crud-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ops-user
