apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: ops-user-readonly-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ops-user-read-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ops-user
