apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: ops-user-efk-binding
  namespace: efk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ops-user-crud-monitoring-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ops-user
