apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-dev-mongo-pvc
  namespace: db-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: openebs-hostpath
