apiVersion: v1
kind: Service
metadata:
  name: db-dev-svc
  namespace: db-dev
  labels:
    app: db-dev
spec:
  selector:
    app: db-dev
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
