apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-dev
  namespace: back-dev
  labels:
    app: back-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-dev
  template:
    metadata:
      labels:
        app: back-dev
    spec:
      priorityClassName: back-dev-priority
      nodeName: k8s-master
      volumes:
      - name: spring-src-vol
        persistentVolumeClaim:
          claimName: back-dev-spring-pvc
      - name: gcp-key-vol
        secret:
          secretName: back-gcp-secret
          items:
          - key: key.json
            path: key.json
      containers:
      - image: harbor.asordk.synology.me/lotus-market/spring:2.0
        name: back-dev-container
        ports:
        - containerPort: 8765
        volumeMounts:
        - name: spring-src-vol
          mountPath: /app/build
        - name: gcp-key-vol
          mountPath: /key/key.json
          subPath: key.json
          readOnly: true
        envFrom:
        - configMapRef:
            name: back-dev-cm
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: back-db-secret
              key: MONGO_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: back-db-secret
              key: MONGO_PASSWORD
