apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: back-dev-sa-rolebinding
  namespace: back-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: get-cm-clusterrole
subjects:
- kind: ServiceAccount
  name: back-dev-sa
  namespace: back-dev
