apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: db-ops-sa-rolebinding
  namespace: db-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: get-cm-clusterrole
subjects:
- kind: ServiceAccount
  name: db-ops-sa
  namespace: db-ops
