FROM gradle:jdk17 AS runtime

WORKDIR /app

COPY gradle gradle
COPY gradlew .
COPY build.gradle .
COPY settings.gradle .
COPY src src

RUN ./gradlew clean assemble --no-daemon

CMD ["./gradlew", "bootRun", "--no-daemon"]
