apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: sec-user-check-clusterbinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sec-user-check-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sec-user
