apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-ops
  namespace: db-ops
  labels:
    app: db-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-ops
  strategy: {}
  template:
    metadata:
      labels:
        app: db-ops
    spec:
      priorityClassName: db-ops-priority
      volumes:
      - name: mongo-pv-storage
        persistentVolumeClaim:
          claimName: db-ops-mongo-pvc
      containers:
      - name: db-ops-container
        image: dealim/lotus-market-mongo:1.3
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-pv-storage
          mountPath: /data/db
        resources:
          requests:
            cpu: "2"
            memory: "3Gi"
          limits:
            cpu: "2"
            memory: "3Gi"
