apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-ops-mongo-pvc
  namespace: db-ops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: openebs-hostpath
