FROM gradle:jdk17 AS runtime

WORKDIR /app

# 필요한 파일 복사
COPY gradle gradle
COPY gradlew .
COPY build.gradle .
COPY settings.gradle .
COPY src src

# 필요한 Gradle 종속성을 미리 다운로드하여 캐싱
RUN ./gradlew clean assemble --no-daemon

# 개발 환경에서 bootRun 실행
CMD ["./gradlew", "bootRun", "--no-daemon"]
