apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: dev-user-front-binding
  namespace: front-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-user-front-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dev-user
