apiVersion: v1
kind: ResourceQuota
metadata:
  name: front-dev-rq
  namespace: front-dev
spec:
  hard:
    requests.cpu: "2"         
    requests.memory: "3Gi"
    limits.cpu: "3"        
    limits.memory: "4Gi"  
---
apiVersion: v1
kind: LimitRange
metadata:
  name: front-dev-lr
  namespace: front-dev
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "1"           
      memory: "1Gi"  
    default:
      cpu: "1"        
      memory: "2Gi"  
    max:
      cpu: "2"
      memory: "3Gi"
