apiVersion: v1
kind: Service
metadata:
  name: front-dev-svc
  namespace: front-dev
  labels:
    app: front-dev
spec:
  selector:
    app: front-dev
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080
status:
  loadBalancer: {}
